REPOSITORIES = [
    {
        "name": "AI System Architect Advisor (R1)",
        "description": "Expert software architecture analysis and recommendations using a dual-model approach combining DeepSeek R1 and Claude.",
        "features": [
            "Dual AI Model Architecture: DeepSeek Reasoner for initial analysis + Claude-3.5 for roadmaps",
            "Comprehensive Analysis: Covers pattern selection, infrastructure, security, and risk assessment",
            "Diverse Domain Support: Real-time systems, Healthcare, Finance, and Multi-tenant SaaS",
            "Implementation Specifications: Detailed roadmaps and technical architectural decisions",
        ],
        "usage": "streamlit run ai_system_architect_r1.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/advanced_ai_agents/single_agent_apps/ai_system_architect_r1",
        "example": "Build a high-frequency trading platform with sub-millisecond latency and 100k TPS.",
        "saasReasoning": "This serves as a 'Virtual CTO' for high-growth tech teams. It cuts down technical planning cycles from weeks to minutes, providing validated architectural patterns and infrastructure cost estimations that are ready for executive review.",
        "tech": "DeepSeek R1, Claude 3.5 Sonnet, Agno, Streamlit",
    },
    {
        "name": "Corrective RAG Agent",
        "description": "A sophisticated LangGraph system that combines retrieval, relevance grading, and web-search to provide highly accurate responses.",
        "features": [
            "Smart Document Retrieval: Uses Qdrant vector store for high-precision matching",
            "Document Relevance Grading: Claude 4.5 Sonnet filters out irrelevant noise",
            "Query Transformation: Automatically optimizes user queries for better search context",
            "Web Search Fallback: Integrates Tavily API when internal documentation is insufficient",
        ],
        "usage": "streamlit run corrective_rag.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/rag_tutorials/corrective_rag",
        "example": "Provide a research paper and ask specific questions; the agent will verify internal facts or find updates online.",
        "saasReasoning": "Ideal for 'High-Stakes Knowledge Bases' where accuracy is non-negotiable. By incorporating a verification loop, it prevents hallucinations, making it safe for enterprise deployment in legal, medical, or regulatory sectors.",
        "tech": "LangGraph, Claude 4.5 Sonnet, Qdrant, OpenAI Embeddings, Tavily",
    },
    {
        "name": "Multi-MCP Agent Router",
        "description": "A specialized multi-agent pattern connecting specialized AI agents to different MCP servers for domain-specific tasks.",
        "features": [
            "4 Specialized Agents: Code Reviewer, Security Auditor, Researcher, and BIM Engineer",
            "MCP Tool Routing: Dedicated access to GitHub, filesystem, and fetch servers",
            "Automatic Intent Classification: Intelligent routing based on user query context",
            "Conversation Memory: Persistent per-agent session history for iterative tasks",
        ],
        "usage": "streamlit run agent_forge.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/mcp_ai_agents/multi_mcp_agent_forge",
        "example": "Perform a security audit of a repository while fetching the latest compliance standards via the Fetch MCP.",
        "saasReasoning": "This is a blueprint for the 'Modular Enterprise Hub'. It allows companies to scale their AI capabilities by simply plugging in new MCP servers and specialized agents, ensuring each agent remains performant and focused.",
        "tech": "Claude 3.5 Sonnet, Anthropic API, MCP (GitHub/Filesystem/Custom), Streamlit",
    },
    {
        "name": "AI Data Analysis Agent",
        "description": "Built using Agno and GPT-4o, this agent enables natural language queries for CSV and Excel files using DuckDB.",
        "features": [
            "File Upload Support: Automatic data type detection and schema inference for CSV/Excel",
            "Natural Language Queries: Converts plain English into complex DuckDB SQL queries",
            "Advanced Analysis: Performs aggregations, filtering, and statistical summaries",
            "Interactive Visualizations: Real-time charting and Streamlit-based result presentation",
        ],
        "usage": "streamlit run ai_data_analyst.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/ai_data_analysis_agent",
        "example": "Upload a sales report and ask: 'Show me the correlation between advertising spend and conversion rates.'",
        "saasReasoning": "A 'No-Code BI' asset for non-technical departments. It removes the need for manual SQL writing or complex Excel pivot tables, allowing operations and marketing teams to query live data directly.",
        "tech": "Agno, GPT-4o, DuckDB, Streamlit, Pandas",
    },
    {
        "name": "AI Consultant Agent",
        "description": "A business strategist providing real-time market research and strategic recommendations via Perplexity AI.",
        "features": [
            "Real-time Web Research: Powered by Perplexity AI for up-to-the-minute market data",
            "Strategic Recommendations: Logic-driven business advice based on current trends",
            "Risk Assessment: Identifies market entry barriers and competitive threats",
            "Citation Support: Provides sources for verified accuracy in reporting",
        ],
        "usage": "adk web",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/ai_consultant_agent",
        "example": "Ask: 'Analyze the growth potential of the sustainable fashion market in Dhaka for 2026.'",
        "saasReasoning": "Commercialized as a 'Market Intel' tool. It cuts research time from weeks to minutes, making it a valuable subscription for entrepreneurs and corporate strategy teams who need fast, data-backed insights.",
        "tech": "Google ADK, Gemini, Perplexity AI",
    },
    {
        "name": "AI VC Due Diligence Team",
        "description": "A 7-stage sequential pipeline for startup investment analysis, providing McKinsey-style reports.",
        "features": [
            "Sequential Pipeline: 7-stage orchestration from research to final memo",
            "Bear/Base/Bull Models: Automated revenue and growth projection charting",
            "Investor Memo Generation: Standardized PDF/HTML artifacts for deal rooms",
            "Automated Infographics: Visual summaries of SWOT and market positioning",
        ],
        "usage": "adk web --project vc_diligence",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/ai_vc_due_diligence",
        "example": "Perform a Series A evaluation of a new Fintech startup including competitive benchmarking.",
        "saasReasoning": "Direct ROI for VC and PE firms. It automates the high-volume initial screening of startups, ensuring that human analysts only spend time on deals that pass the automated due diligence filters.",
        "tech": "Google ADK, Gemini 3 Pro/Flash",
    },
    {
        "name": "AI Finance Agent",
        "description": "Structured financial insights and stock analysis using xAI Grok and YFinance.",
        "features": [
            "Real-time Stock Data: Direct integration with Yahoo Finance for live price fetching",
            "Formatted Financial Tables: Structured output of balance sheets and stock comparisons",
            "AgentOS Control Plane: Autonomous tool-calling for cross-sector analysis",
            "Grok Reasoning: High-speed synthesis of financial news and market indicators",
        ],
        "usage": "python xai_finance_agent.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/ai_finance_agent",
        "example": "Query: 'Compare the P/E ratios and debt-to-equity of the top 5 semiconductor stocks.'",
        "saasReasoning": "A 'Financial Co-pilot' for wealth management firms and retail investors. It allows for high-velocity screening of equities based on live technical and fundamental data.",
        "tech": "xAI Grok-4 Fast, YFinance, DuckDuckGo",
    },
    {
        "name": "AI Product Launch Intelligence",
        "description": "GTM strategist team using Agno and Firecrawl to turn web data into launch insights.",
        "features": [
            "Competitor Analysis: Scrapes and analyzes rival GTM strategies and positioning",
            "Market Sentiment: Evaluates public perception across social and review platforms",
            "GTM Roadmap Generation: Automates the creation of launch-ready markdown reports",
            "Firecrawl Integration: Handles complex JS-rendered web pages for data extraction",
        ],
        "usage": "streamlit run product_launch_intelligence_agent.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/ai_product_launch_intelligence",
        "example": "Input a competitor's URL to extract their pricing tiers and core feature differentiation.",
        "saasReasoning": "Reduces product-market-fit risk. It provides GTM teams with a 'live' competitive dashboard, ensuring their launch strategy accounts for the latest rival moves and market pricing.",
        "tech": "Agno Team, Firecrawl, GPT-4o",
    },
    {
        "name": "AI Sales Intelligence Team",
        "description": "Generates professional competitive battle cards and objection handling scripts in real-time.",
        "features": [
            "Battle Card Generation: HTML-ready cards with 'We Win' vs 'They Win' sections",
            "Objection Scripts: Step-by-step talk tracks for sales reps to handle pushback",
            "Killer Questions: Strategic questions to ask prospects to reveal rival weaknesses",
            "State Management: Passes research data through a multi-agent coordinator",
        ],
        "usage": "adk web (Sales Intel module)",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/ai_sales_intelligence_agent",
        "example": "Generate a battle card for a prospect currently using a legacy ERP system.",
        "saasReasoning": "A high-leverage 'Sales Enablement' SaaS. It directly increases revenue by empowering reps with the technical and strategic knowledge needed to win competitive displacement deals.",
        "tech": "Google ADK, Gemini 3, Google Search Tool",
    },
    {
        "name": "AI Competitor Intelligence Agent",
        "description": "Extracts structured data from competitor websites to find market gaps.",
        "features": [
            "Competitor Discovery: Uses Exa AI neural search to find rivals beyond keywords",
            "Structured Extraction: Turns competitor websites into clean JSON/CSV data",
            "Comparison Table Generation: Automated feature-by-feature benchmarking",
            "Pricing Strategy Analysis: Identifies hidden discounts or tiered pricing models",
        ],
        "usage": "streamlit run ai_competitor_analyser.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/ai_competitor_intelligence",
        "example": "Identify market gaps in the Dhaka e-commerce grocery sector by analyzing top 5 rivals.",
        "saasReasoning": "A 'Live Strategy' tool for executives. It provides an automated, always-on view of the competitive landscape, removing the need for manual, periodic market research projects.",
        "tech": "Agno, Firecrawl, Exa AI, GPT-4o",
    },
    {
        "name": "AI Recruitment Agent Team",
        "description": "Automates resume screening, technical evaluation, and interview scheduling.",
        "features": [
            "Resume Analyzer: RAG-based skill matching vs job descriptions",
            "Scheduling Coordinator: Automated Zoom/Calendar integration for booking",
            "Technical Assessment: Generates role-specific questions and scores answers",
            "Full-Service Simulation: Operates as a multi-agent HR department workflow",
        ],
        "usage": "streamlit run ai_recruitment_agent_team.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/ai_recruitment_agent_team",
        "example": "Filter 500 applicants for a DevOps role to find the top 5 with Kubernetes expertise.",
        "saasReasoning": "Ideal for recruiting agencies and HR departments. This agent handles the 'low-value' filtering work, allowing recruiters to focus solely on high-value candidate engagement.",
        "tech": "Phidata, GPT-4o, Zoom API, Gmail API",
    },
    {
        "name": "Chat with Gmail Inbox",
        "description": "RAG-powered app to analyze and answer questions based on your Gmail content.",
        "features": [
            "Oauth2 Security: Secure integration with the Google Gmail API",
            "RAG-Powered Q&A: Deep semantic search over thousands of email threads",
            "Context Retrieval: Summarizes recent invoices, threads, or flight details",
            "Interactive Streamlit UI: User-friendly chat interface for personal mail",
        ],
        "usage": "streamlit run chat_gmail.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/chat_with_gmail",
        "example": "Ask: 'Find all correspondence regarding the apartment lease renewal and summarize terms.'",
        "saasReasoning": "A productivity SaaS for power users. It eliminates the 'search bar fatigue' in traditional email clients by allowing for natural language synthesis of buried information.",
        "tech": "Python, RAG, OpenAI API, Google Cloud Console",
    },
    {
        "name": "Chat with GitHub Repo",
        "description": "Analyze repository content using RAG and Embedchain for instant code understanding.",
        "features": [
            "Knowledge Base Creation: Automatically indexes GitHub repos via API",
            "Natural Language Search: 'How does the payment logic work?' queries",
            "Embedchain Integration: Sophisticated chunking and embedding for code logic",
            "Real-time Insights: Immediate analysis of repository health and activity",
        ],
        "usage": "streamlit run chat_github.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/chat_with_github",
        "example": "Point the agent to a legacy codebase to identify where the database connection is handled.",
        "saasReasoning": "Targeted at large-scale software onboarding. It significantly reduces 'ramp-up' time for new developers by providing an instant technical expert on any repository.",
        "tech": "Embedchain, OpenAI, GitHub API, ChromaDB",
    },
    {
        "name": "AI Travel Agent with Memory",
        "description": "An intelligent travel assistant that maintains persistent memory of user preferences.",
        "features": [
            "Persistent Memory: Mem0 integration for cross-session preference tracking",
            "Chat-based Planning: Dynamic itinerary creation based on ongoing dialogue",
            "Preference Vectoring: Learns user habits (e.g., budget-friendly vs luxury) over time",
            "Contextual Awareness: Remembers past trip feedback to improve future suggestions",
        ],
        "usage": "streamlit run travel_agent_memory.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/starter_ai_agents/ai_travel_agent_memory",
        "example": "Plan a trip to Japan, knowing the user previously mentioned a preference for quiet cities.",
        "saasReasoning": "The ultimate 'Loyalty' engine. By remembering user traits, this agent becomes more valuable over time, creating a powerful moat against generic, non-personalized travel competitors.",
        "tech": "GPT-4o, Mem0, Qdrant",
    },
    {
        "name": "MCP Travel Planner Team",
        "description": "A sophisticated planner using MCP for real-time Airbnb and Google Maps data.",
        "features": [
            "Airbnb Integration: Fetches live listings and pricing via the Airbnb MCP",
            "Google Maps Tooling: Real-time distance, time, and route calculations",
            "Calendar Export: Automatically generates .ics files for itinerary management",
            "Multi-Agent Execution: Coordinates between booking and logistics experts",
        ],
        "usage": "streamlit run app.py",
        "github": "https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/mcp-travel-planner",
        "example": "Find an Airbnb in Paris near a Metro station for under $150 and map the walk.",
        "saasReasoning": "Moves from 'Recommendation' to 'Execution'. By using live protocols (MCP), it provides verified, actionable data that can be used for direct booking and logistical planning.",
        "tech": "Airbnb MCP, Google Maps MCP, GPT-4o, Streamlit",
    },
]